Repository GitTools/GitVersion, pull requests merged in 2019-10, with the labels that each got.

#1835 Docs Update - Azure DevOps piplines yml example
  docs/build-server-support/build-server/azure-devops
Labels: documentation

#1847 Add the xml namespace to work with MSBuild v14
  src/GitVersionTask/build/GitVersionTask.props
  src/GitVersionTask/build/GitVersionTask.targets
  src/GitVersionTask/buildMultiTargeting/GitVersionTask.props
  src/GitVersionTask/buildMultiTargeting/GitVersionTask.targets
Labels: bug

#1871 adds Preview suffix to VSIX task name when appropriate
  build/pack.cake
  src/GitVersionVsixTask/GitVersionTask/task.json
Labels: improvement
