Repository GitTools/GitVersion, pull requests merged in 2019-08, with the labels that each got.

#1741 Fix current branch variable name for GitLab CI
  src/GitVersionCore/BuildServers/GitLabCi.cs
Labels: improvement

#1767 Allow head to move for dynamic repositories
  src/GitVersionCore.Tests/DynamicRepositoryTests.cs
  src/GitVersionCore.Tests/IntegrationTests/RemoteRepositoryScenarios.cs
  src/GitVersionCore/GitPreparer.cs
  src/GitVersionCore/Helpers/GitRepositoryHelper.cs
Labels: bug

#1777 Only append /config if the user specified a configFilePath
  src/GitVersionTfsTask/GitVersion.ts
Labels: bug

#1762 Add -nonormalize option to disable normalize function
  docs/build-server-support/build-server-support.md
  src/GitVersionCore/ExecuteCore.cs
  src/GitVersionExe.Tests/ArgumentParserTests.cs
  src/GitVersionExe/ArgumentParser.cs
  src/GitVersionExe/Arguments.cs
  src/GitVersionExe/HelpWriter.cs
  src/GitVersionExe/SpecifiedArgumentRunner.cs
Labels: feature

#1787 Fixed entrypoint for github actions
  src/Docker/Dockerfile
Labels: improvement
