Repository GitTools/GitVersion, pull requests merged in 2021-01, with the labels that each got.

#2510 Update icon url
  build/nuspec/GitVersion.Portable.nuspec
Labels: improvement

#2517 Add banner
  README.md
Labels: documentation, improvement

#2569 Added CodeQL workflow
  .github/workflows/codeql-analysis.yml
Labels: build
