Repository GitTools/GitVersion, pull requests merged in 2024-11, with the labels that each got.

#4296 (build) use sdk 9.0.100
  global.json
Labels: build

#4279 Sunset .net 6.0
  build/.run/UnitTest (6.0).run.xml
  build/common/Utilities/Constants.cs
  docs/input/docs/reference/build-servers/bitbucket-pipelines.md
  src/Directory.Build.props
  src/GitVersion.MsBuild/GitVersion.MsBuild.csproj
Labels: improvement

#4301 #4299 - add new schemas for 6.11.*
  schemas/6.1/GitVersion.configuration.json
  schemas/6.1/GitVersion.json
  src/GitVersion.Schema/Program.cs
Labels: build

#4308 Update the commit-message behavior docs
  docs/input/docs/reference/version-increments.md
Labels: documentation

#4317 fix: Typo in continuous-deployment.md
  docs/input/docs/reference/modes/continuous-deployment.md
Labels: documentation

#4324 (dependabot) Add .NET SDK to Dependabot configuration
  .github/dependabot.yml
Labels: build
